apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: iam
  name: iam
spec:
  ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 8888
  selector:
    k8s-app: iam
  sessionAffinity: None
  type: LoadBalancer
